---
# tasks file for osp.servers
- name: Create instances
  os_server:
    cloud: openstack
    name: "{{ __inst.name }}"
    image: "{{ __inst.image }}"
    key_name: "{{ __inst.key_name }}"
    flavor: "{{ __inst.flavor }}"
    security_groups: "{{ __inst.security_group }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group={{ __inst.meta.group }},deployment_name={{ __inst.meta.deployment_name }}"
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  loop: "{{ query('dict' ,'osp_servers') }}"
  # lookup('dict', key_dict, wantlist=True)
  loop_control:
    loop_var: __inst
    

- name: Add floating IP to instance
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: 
    network: ext_network
    wait: true
    timeout: 200
  